### ISSUE TITLE
Zipulses configuration Z2M

### ISSUE THREAD

**Issue by nlindblo** [fairecasoimeme/ZiPulses#12]
Hello,

I have installed Zipulses in my Gazer meter and configured zigbee2mqtt in a way that I believe is correct. I am receiving pulses but the values are in whole numbers and the energy sensor does not have a unitOfMeasure, meaning I dont seem to be able to add it to the Energy dashboard. Here is my configuration and output if someone have an idea of where I am going wrong, my objective would be to have the numbers to come in as m3 into HA, is there any further configuration I need to do ?

Apologies for writing in English as I'm not French speaking, feel free to respond in French and I will Google translate

![Screenshot 2023-06-13 at 10 54 27](https://github.com/fairecasoimeme/ZiPulses/assets/9881339/da34792a-0f8b-458c-bb13-f535999d772d)

![Screenshot 2023-06-13 at 10 56 44](https://github.com/fairecasoimeme/ZiPulses/assets/9881339/9ee1613f-775d-4043-ac3d-1516cb57c7f2)

![Screenshot 2023-06-13 at 10 57 54](https://github.com/fairecasoimeme/ZiPulses/assets/9881339/d03b1726-d70c-4930-96c3-ae983e61a69d)

![Screenshot 2023-06-13 at 10 59 33](https://github.com/fairecasoimeme/ZiPulses/assets/9881339/970fc5a7-b2cb-4f9a-94ea-51967a060a8d)

**Comment by fairecasoimeme** [comment]
hi, you have to reconfig the device as explained here : 
https://github.com/fairecasoimeme/ZiPulses#z2m

**Comment by nlindblo** [comment]
I actually had followed the instruction for the reconfiguration, but to confirm I re-paired the device and did it another time and now the values seem to come through in the right decimal format. However, the energy sensor does still not have a UnitOfMeasurement or device_class, is this supposed to be configured manually or come from Z2M ? These are the sensors that have been created

![Screenshot 2023-06-13 at 15 12 39](https://github.com/fairecasoimeme/ZiPulses/assets/9881339/1d66fab2-29aa-4e63-b6f5-cc01a3d52107)

**Comment by raspbeguy** [comment]
Can confirm the behaviour. If you're using Home Assistant, workaround is to create another device in HA config file:

```yaml
template:
  - sensor:
      - name: "Gas_meter"
        unit_of_measurement: "m³"
        device_class: "gas"
        state_class: "total_increasing"
        state: "{{ states('sensor.compteur_gaz_energy')|float }}"
        availability: "{{ states('sensor.compteur_gaz_energy') not in ['none', 'unknown', 'unavailable'] }}"
```

**Comment by beauby** [comment]
I am facing the same issue: setting `unitOfMeasure` to `m3` does not cause the `energy` entity to have `unit_of_measurement` set to `m3`. Am I misunderstanding the role of `unitOfMeasure`?

**Comment by nlindblo** [comment]
Its been some time since I looked at this, but I checked just now and I have the unit set to m3 in Z2M and then I have this template sensor, and it seem to generate an accurate result

````
    - sensor:
        - name: "Engie Gas kWh"
          availability: "{{ ((states('sensor.zipulses_device_energy') | is_number )) }}"
          icon: mdi:gas-burner
          unit_of_measurement: "kWh"
          device_class: energy
          state_class: total_increasing
          state: >
            {% set gasm3 = states('sensor.zipulses_device_energy') | float %}
            {% set coeff = states('input_number.grdf_gas_coefficient') | float %}
            {{ (gasm3  * coeff) | round(2, default=0) }}
````
