### ISSUE TITLE
Le compteur ne prend pas en compte le facteur multiplicateur

### ISSUE THREAD

**Issue by jeanaaaa** [fairecasoimeme/ZiPulses#3]
**Problème :**
Le compteur est incrémenté d'une unité au lieu de prendre en compte le facteur multiplicateur

**Contexte :**
- Configuration via Zigbee2mqtt
- J'utilise ZiPluses avec le compteur Gazpar et j'ai positionné le facteur multiplicateur à 10 et l'unité à L.

**Tests effectués sans succès :**
- Réinitialiser ZiPluses avec le bouton "Reset"
- Ré-appairer ZiPluses 
- Retirer la pile
- Changer le facteur multiplicateur à une autre valeur

**Données remontées via MQTT :**
Malgré le facteur multiplicateur configuré sur 10, le compteur "energy" n'est incrémenté que d'une valeur à chaque impulsion du compteur Gazpar.
```
Received 08:30:43

    QoS: 0
    Payload:

    divisor: 2
    energy: 5
    linkquality: 5
    multiplier: 10
    temperature: null
    unitOfMeasure: L (litre)
    voltage: null

Received 08:30:43

    QoS: 0
    Payload:

    divisor: 2
    energy: 6
    linkquality: 5
    multiplier: 10
    temperature: null
    unitOfMeasure: L (litre)
    voltage: null

```
