### ISSUE TITLE
Régler unit_of_measure sur Home Assistant

### ISSUE THREAD

**Issue by pierreprinetti** [fairecasoimeme/ZiPulses#36]
Bonjour,

J'ai connecté le Zipulses en ZHA sur mon Home Assistant (Core v2024.9.3) qui se trouve à moins de deux mètres du capteur. Les données de consommation remontent bien.

Le Zipulses par défault remonte l'unité kWh, alors que si je compare ça avec les données de GRDF, j'ai l'impression que c'est plutôt des centièmes de m³ que Gazpar exprime.

Je voudrais donc utiliser la fonction "Manage Zigbee device" pour entrer:
* dans `Metering (Endpoint id: 1, Id: 0x0702, Type: in)`:
  * `unit_of_measure` (id: 0x0300)` à `1`
  * `divisor (id: 0x0302)` à 100

Or quand j'envoie "Write attribute" (et que je clique le bouton "Link" sur mon ZiPulse, et que la LED clignote une fois), le bouton tourne au rouge et une erreur s'affiche:

> Failed to perform the action zha/set_zigbee_cluster_attribute. Failed to set attribute: value: True attribute: 768 cluster_id: 1794 endpoint_id: 1

Qu'est-ce qui peut avoir mal tourné?

Merci.

![signal-2024-09-29-152637](https://github.com/user-attachments/assets/47de8955-72d6-4415-95b0-0b7148ed2090)

**Comment by pierreprinetti** [comment]
Alors après plusieurs tentatives, j'ai enfin un ack positif de la part the Home Assistant. Appuyer sur "Link" une fois n'était pas suffisant; je clique "Write attribute", j'appuye trois ou quatre fois, et à ce point j'ai environ 20% de chances que le bouton tourne au vert sans erreur.

Dans tous les cas, rien ne change dans le Zipulse. Les données sont toujours en kWh et "Read" retourne enum8.

**Comment by pierreprinetti** [comment]
En attendant une solution pour régler le problème à la base, voici comment j'ai finalement ajouté un senseur "template" dans ma configuration HomeAsssistant:

```yaml
# dans configuration.yaml

# [...]

template:
  - sensor:
    - name: "Gazpar"
      unique_id: "lixee_zipulses_summation_delivered_m3"
      unit_of_measurement: "m³"
      device_class: gas
      state_class: total_increasing
      state: "{{ ( states('sensor.lixee_zipulses_summation_delivered') | float ) / 100 }}"
```

J'ai ensuite ajouté ce nouveau senseur virtuel au volet "Energie" pour visualiser ma consommation en gaz.
