### ISSUE TITLE
Configuration avec Home Assistant 2023.3.6 et Zigbee2Mqtt 1.30.2-1

### ISSUE THREAD

**Issue by Gonioul** [fairecasoimeme/ZiPulses#4]
Bon,
Mon chemin de croix se termine, c'est un peu la pêche aux infos à droite à gauche, mais si ça peut aider...

Impossible d’appairer le ZiPulse avec la version actuelle de Zigbee2Mqtt sans ajouter le converter:
https://github.com/fairecasoimeme/ZiPulses/issues/2
(à noter que le module a crashé une fois après cet ajout)

Ensuite, le capteur n'est pas proposé dans le dashboard énergie (problème d'unité je suppose), le multiplicateur ne fonctionne pas, etc..

Je pars du principe que:
- 1 impulsion sensor.gazpar_energy = 10 L
- 1 L = 0.01 m³

En approximant les prix et l'altitude:
- 1 m³ de gaz naturel = 10 kWh

Et donc:
- 0.01 m³ de gaz naturel = 0.1 kWh
- 1 L de gaz naturel = 0.1 kWh

Au final:
- 1 impulsion = 1 kWh

Et donc on se contente de customiser le sensor 'sensor.gazpar_energy':

```
homeassistant:
  customize_glob:
    sensor.gazpar_energy:
      device_class: energy
      unit_of_measurement: 'kWh'
```

**Comment by ellmout** [comment]
Une impulsion = 0,10 kWh
Car une impulsion de gazpar = 10 L
Dans 1 m3, il y a 1 000 L
1 impulsion x 10L / 1000L pour avoir des m3 x 10 environ pour le coefficient = 0,1 kWh

**Comment by Gonioul** [comment]
Effectivement j'ai été trompé par les données gdrf, mais bon pour l'instant le coefficient ne marche pas...

**Comment by PEGARifrouf** [comment]
Bonjour,

Dans l'idée j'aurais créé un input number dans HA pour régler le coefficient de conversion (en attendant de pouvoir le régler directement avec Z2m)

Ensuite avec un sensor template on peut faire un conversion plus precise impulsion => kwh

En récupérant ici le facteur de conversion de votre commune :
[Lien vers GRDF](https://www.grdf.fr/particuliers/coefficient-conversion-commune)

Je reçois le Zipulse dans quelques jours je viendrais poster le template si ça marche bien.

**Comment by ellmout** [comment]
Voici mes templates pour avoir en m3 et en kWh, qu'on peut ajouter au tableau energie.

```yaml
template:
   - sensor:
      - name: "Gaz Energy"
        unit_of_measurement: 'kWh'
        state: "{{ states('sensor.zipulses_energy') | int * 10 / 1000 * 10.92 | round(3) }}"
        device_class: energy
        state_class: total_increasing
   - sensor:
      - name: "Gaz Volume"
        unit_of_measurement: 'm³'
        state: "{{ states('sensor.zipulses_energy') | int * 10 / 1000 | round(3) }}"
        device_class: gas
        state_class: total_increasing
```

10.92 = mon facteur de conversion, il est aussi sur sa facture de Gaz
